include:
  - docker-compose.yml

services:

  frontend:
    build:
      target: production
    volumes:
      - frontend_build:/usr/share/nginx/html

  # === Infrastructure ===

  nginx:
    build:
      target: production
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      frontend:
        condition: service_completed_successfully
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
      - ./nginx/cert:/etc/nginx/cert:ro

volumes:
  frontend_build:
