name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: 'frontend/.nvmrc'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2
        with:
          version: v5.0.0

      - name: Prepare env file
        run: cp .env.example .env

      - name: Install dependencies
        run: make ci

      - name: Build docker containers
        run: make build

      - name: Run tests
        run: make test

      - name: Lint and type-check
        run: make lint-compile
